### ISSUE TITLE
Small bug with mapping feature

### ISSUE THREAD

**Issue by CuckooRules** [syntax53/Nightmare-Redux#6]
If a room has an exit with type Hidden but all the parameters are left as 0, MME shows this as an exit as "Hidden/Unknown".  This is an error, as MUD does not actually create any exit (as far as I can tell).

[Screenshot example](http://i.imgur.com/F4NcVQK.jpg)

**Comment by syntax53** [comment]
wrong project, but i'll get it :)

**Comment by CuckooRules** [comment]
oops sorry i just hit new issue i still had the old window open

**Comment by syntax53** [comment]
Actually, this is NMR because the para's aren't exported to MME.  NMR put what it needs to on export.  However, I'm saying this isn't a bug because really it's editor error :).  However, I'll verify that the exit isn't actually accessible and do something to correct it.  Looks like there are 3 similar situations in stock dats -- 1/515, 517, and 592.

**Comment by CuckooRules** [comment]
i fully agree its a programming error but your mappings interpretation that
there is an exit is still mislesding to players who have no idea how any of
this works :)

**Comment by syntax53** [comment]
fixed for next release.
